### ISSUE TITLE
NBA 2K20 or any older ones.

### ISSUE THREAD

**Issue by galaxyninjaa** [masagrator/NXGraphicsPatches#37]
**Full game title**
NBA 2K20

60 FPS mod?

**Describe many informations about this topic**
It currently runs at 30 fps
60 would be a big difference in a sports game

**Comment by staringstar** [comment]
DM me in discord so i can make it for you because i need exefs. here is my username zakaria#4420 .

**Comment by masagrator** [comment]
[NBA2K2020-1.07.zip](https://github.com/masagrator/NXGraphicsPatches/files/4466191/NBA2K2020-1.07.zip)
This for NBA 2K20 1.07
Go with highest clocks possible, play only with handheld flag.
Matches are between 50 and 60 FPS at max clocks. In cutscenes etc. it can drop to 30 FPS. 
After unlocking 60 FPS game is first GPU bound, but not so below is CPU Core 0 bound.  
Changing resolution doesn't work in exefs, Dynamic resolution is stored in game archives as Dynamic_Resolution_Adjustment.json, but I can't extract it. But dropping resolution would not help with getting locked 60 FPS in matches because of CPU.
